---
title: "Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r}
data("nyc_airbnb")

nyc_airbnb =  
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>% 
  drop_na(rating)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choices = nyc_airbnb %>% pull(neighbourhood_group) %>%  unique()

selectInput(
  "borough_choice",
  h3("Borough Choice"),
  choices = borough_choices
)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

